FROM python:3.9

ENV PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=on

WORKDIR /app/bot/

COPY requirements.txt /app/bot/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/bot/requirements.txt

COPY . /app

CMD ["python", "bot.py"]
